# Generated by Django 3.1.6 on 2021-03-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0006_weightclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
