# Generated by Django 3.1.6 on 2021-03-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0008_fighter_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='category',
        ),
        migrations.AddField(
            model_name='fighter',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fytnet.category'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='weight_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fytnet.weightclass'),
        ),
    ]
