# Generated by Django 3.1.6 on 2021-03-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_gym_categorys'),
        ('fytnet', '0009_auto_20210318_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='trains_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.gym'),
        ),
    ]
