# Generated by Django 3.1.6 on 2021-03-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_auto_20210324_1158'),
        ('fytnet', '0010_fighter_trains_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='trains_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='gym.gym'),
        ),
    ]
