# Generated by Django 3.1.6 on 2021-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0012_auto_20210325_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='fight_style',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='titles',
            field=models.CharField(max_length=200),
        ),
    ]
