# Generated by Django 3.1.6 on 2021-03-26 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fytnet', '0013_auto_20210326_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='fighter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
