# Generated by Django 3.1.6 on 2021-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0015_auto_20210326_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='email',
            field=models.CharField(default='user@fytletic.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='nick_name',
            field=models.CharField(default='Fytletic Fighter', max_length=50),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='whatsapp',
            field=models.CharField(default='07555555555', max_length=50),
        ),
    ]
