# Generated by Django 3.1.6 on 2021-03-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0019_auto_20210327_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='fighter',
            new_name='user',
        ),
    ]
