# Generated by Django 3.1.6 on 2021-03-27 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fytnet', '0021_auto_20210327_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighter',
            old_name='video',
            new_name='video_1',
        ),
        migrations.AddField(
            model_name='fighter',
            name='video_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='video_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='video_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='video_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
