# Generated by Django 3.1.6 on 2021-03-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0023_auto_20210328_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
