# Generated by Django 3.1.6 on 2021-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0024_fighter_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='email',
            field=models.CharField(blank=True, default='fighter@fytletic.com', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='nick_name',
            field=models.CharField(blank=True, default='Fytnet PRO Fighter', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='whatsapp',
            field=models.CharField(blank=True, default='07555555555', max_length=50, null=True),
        ),
    ]
