# Generated by Django 3.1.6 on 2021-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0025_auto_20210328_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weight',
            field=models.IntegerField(blank=True, help_text='This is the weight of the fighter', null=True),
        ),
    ]
