# Generated by Django 3.1.6 on 2021-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fytnet', '0027_auto_20210329_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='profile_photo_main',
            field=models.ImageField(help_text='The main photo for the Fighter profile header', upload_to='media/%Y/%m/%d'),
        ),
    ]
