# Generated by Django 3.1.6 on 2021-03-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_restricted',
            field=models.BooleanField(default=True, help_text='Restrict access to users creating multiple fighters and gyms'),
        ),
    ]
