# Generated by Django 3.1.6 on 2021-03-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_is_restricted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_restricted',
            new_name='is_unrestricted',
        ),
    ]
