# Generated by Django 3.1.6 on 2021-03-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210330_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_unrestricted',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='multi_author',
            field=models.BooleanField(default=False, help_text='Restrict access to users creating multiple fighters and gyms'),
        ),
    ]
