# Generated by Django 3.1.6 on 2021-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210330_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='multi_author',
            field=models.BooleanField(default=False, help_text='Multi Authors can add more than one fighter and gym profile'),
        ),
    ]
