# Generated by Django 3.1.6 on 2021-03-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'NewsCategories'},
        ),
    ]
