# Generated by Django 3.1.6 on 2021-03-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210311_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
