# Generated by Django 3.1.6 on 2021-03-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
