# Generated by Django 3.1.6 on 2021-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210316_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorys',
            field=models.ManyToManyField(to='news.Category'),
        ),
    ]
