# Generated by Django 3.1.6 on 2021-03-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='NewsCategory',
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'News Categories'},
        ),
    ]
