# Generated by Django 3.1.6 on 2021-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('whatsapp', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('profile_photo_main', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.URLField(blank=True, null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('facebook', models.URLField(blank=True, max_length=1024, null=True)),
                ('instagram', models.URLField(blank=True, max_length=1024, null=True)),
                ('twitter', models.URLField(blank=True, max_length=1024, null=True)),
                ('web', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
