# Generated by Django 3.1.6 on 2021-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_gym_image_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='image_test',
        ),
        migrations.AddField(
            model_name='gym',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='gym',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='gym',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='gym',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
