# Generated by Django 3.1.6 on 2021-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_auto_20210317_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
