# Generated by Django 3.1.6 on 2021-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_gym_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='gym_owner',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='gym',
            name='gym_owner_name',
            field=models.CharField(default='Fytletic Gym Owner', max_length=50),
            preserve_default=False,
        ),
    ]
