# Generated by Django 3.1.6 on 2021-03-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20210317_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='categorys',
            field=models.ManyToManyField(to='gym.Category'),
        ),
    ]
