# Generated by Django 3.1.6 on 2021-03-24 11:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20210318_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
