# Generated by Django 3.1.6 on 2021-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_auto_20210324_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='GymType',
        ),
        migrations.AlterModelOptions(
            name='gymtype',
            options={'verbose_name_plural': 'Gym Types'},
        ),
        migrations.RemoveField(
            model_name='gym',
            name='categories',
        ),
        migrations.AddField(
            model_name='gym',
            name='gym_type',
            field=models.ManyToManyField(to='gym.GymType'),
        ),
    ]
