# Generated by Django 3.1.6 on 2021-03-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_auto_20210325_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymtype',
            options={'verbose_name_plural': 'GymTypes'},
        ),
    ]
