# Generated by Django 3.1.6 on 2021-03-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_auto_20210327_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='gym',
            new_name='user',
        ),
    ]
