# Generated by Django 3.1.6 on 2021-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_auto_20210329_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_photo_main',
            field=models.ImageField(help_text='Main gym photo displayed as the header to the profile', upload_to='media/%Y/%m/%d'),
        ),
    ]
