# Generated by Django 3.1.6 on 2021-03-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0020_auto_20210330_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_photo_main',
            field=models.ImageField(blank=True, help_text='Main gym photo displayed as the header to the profile', null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
