# Generated by Django 3.1.6 on 2021-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210217_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memberproduct',
            field=models.BooleanField(default=False),
        ),
    ]
